# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wizard_system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wizard_system.proto',
  package='WizardSystem',
  syntax='proto3',
  serialized_options=b'\252\002\025WizardSystem.Protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13wizard_system.proto\x12\x0cWizardSystem\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\timageData\x18\x03 \x01(\x0c\"\x15\n\x05Magic\x12\x0c\n\x04type\x18\x01 \x01(\t\"\'\n\x11MessageMacAddress\x12\x12\n\nmacAddress\x18\x01 \x01(\t\"\x92\x01\n\rMessageResult\x12=\n\x06result\x18\x01 \x01(\x0e\x32-.WizardSystem.MessageResult.MessageResultType\x12\x15\n\rresultMessage\x18\x02 \x01(\t\"+\n\x11MessageResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"\x8e\x01\n\x0f\x43omputerControl\x12\x42\n\x07\x63ontrol\x18\x01 \x01(\x0e\x32\x31.WizardSystem.ComputerControl.ComputerControlType\"7\n\x13\x43omputerControlType\x12\t\n\x05START\x10\x00\x12\x0b\n\x07RESTART\x10\x01\x12\x08\n\x04STOP\x10\x02\"\xb2\x01\n\x0eProgramControl\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x13\n\x0bprocessName\x18\x03 \x01(\t\x12@\n\x07\x63ontrol\x18\x04 \x01(\x0e\x32/.WizardSystem.ProgramControl.ProgramControlType\")\n\x12ProgramControlType\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\"/\n\tHeartBeat\x12\x11\n\tTimestamp\x18\x01 \x01(\t\x12\x0f\n\x07Message\x18\x02 \x01(\t\"\\\n\x0bPerformance\x12\x10\n\x08\x43puUsage\x18\x01 \x01(\x02\x12\x13\n\x0bMemoryUsage\x18\x02 \x01(\x02\x12\x14\n\x0cNetworkUsage\x18\x03 \x01(\x02\x12\x10\n\x08GpuUsage\x18\x04 \x01(\x02\x32\x8d\x01\n\rWizardService\x12=\n\x11PostMagicImageRaw\x12\x13.WizardSystem.Image\x1a\x13.WizardSystem.Magic\x12=\n\x11PostMagicImagePng\x12\x13.WizardSystem.Image\x1a\x13.WizardSystem.MagicB\x18\xaa\x02\x15WizardSystem.Protobufb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_MESSAGERESULT_MESSAGERESULTTYPE = _descriptor.EnumDescriptor(
  name='MessageResultType',
  full_name='WizardSystem.MessageResult.MessageResultType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=326,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_MESSAGERESULT_MESSAGERESULTTYPE)

_COMPUTERCONTROL_COMPUTERCONTROLTYPE = _descriptor.EnumDescriptor(
  name='ComputerControlType',
  full_name='WizardSystem.ComputerControl.ComputerControlType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESTART', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=459,
  serialized_end=514,
)
_sym_db.RegisterEnumDescriptor(_COMPUTERCONTROL_COMPUTERCONTROLTYPE)

_PROGRAMCONTROL_PROGRAMCONTROLTYPE = _descriptor.EnumDescriptor(
  name='ProgramControlType',
  full_name='WizardSystem.ProgramControl.ProgramControlType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=654,
  serialized_end=695,
)
_sym_db.RegisterEnumDescriptor(_PROGRAMCONTROL_PROGRAMCONTROLTYPE)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='WizardSystem.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='WizardSystem.Image.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='WizardSystem.Image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageData', full_name='WizardSystem.Image.imageData', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=156,
)


_MAGIC = _descriptor.Descriptor(
  name='Magic',
  full_name='WizardSystem.Magic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='WizardSystem.Magic.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=179,
)


_MESSAGEMACADDRESS = _descriptor.Descriptor(
  name='MessageMacAddress',
  full_name='WizardSystem.MessageMacAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='macAddress', full_name='WizardSystem.MessageMacAddress.macAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=220,
)


_MESSAGERESULT = _descriptor.Descriptor(
  name='MessageResult',
  full_name='WizardSystem.MessageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='WizardSystem.MessageResult.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resultMessage', full_name='WizardSystem.MessageResult.resultMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGERESULT_MESSAGERESULTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=369,
)


_COMPUTERCONTROL = _descriptor.Descriptor(
  name='ComputerControl',
  full_name='WizardSystem.ComputerControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='control', full_name='WizardSystem.ComputerControl.control', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPUTERCONTROL_COMPUTERCONTROLTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=514,
)


_PROGRAMCONTROL = _descriptor.Descriptor(
  name='ProgramControl',
  full_name='WizardSystem.ProgramControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='WizardSystem.ProgramControl.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileName', full_name='WizardSystem.ProgramControl.fileName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processName', full_name='WizardSystem.ProgramControl.processName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='control', full_name='WizardSystem.ProgramControl.control', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROGRAMCONTROL_PROGRAMCONTROLTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=695,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='HeartBeat',
  full_name='WizardSystem.HeartBeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='WizardSystem.HeartBeat.Timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Message', full_name='WizardSystem.HeartBeat.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=697,
  serialized_end=744,
)


_PERFORMANCE = _descriptor.Descriptor(
  name='Performance',
  full_name='WizardSystem.Performance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CpuUsage', full_name='WizardSystem.Performance.CpuUsage', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MemoryUsage', full_name='WizardSystem.Performance.MemoryUsage', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NetworkUsage', full_name='WizardSystem.Performance.NetworkUsage', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='GpuUsage', full_name='WizardSystem.Performance.GpuUsage', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=746,
  serialized_end=838,
)

_MESSAGERESULT.fields_by_name['result'].enum_type = _MESSAGERESULT_MESSAGERESULTTYPE
_MESSAGERESULT_MESSAGERESULTTYPE.containing_type = _MESSAGERESULT
_COMPUTERCONTROL.fields_by_name['control'].enum_type = _COMPUTERCONTROL_COMPUTERCONTROLTYPE
_COMPUTERCONTROL_COMPUTERCONTROLTYPE.containing_type = _COMPUTERCONTROL
_PROGRAMCONTROL.fields_by_name['control'].enum_type = _PROGRAMCONTROL_PROGRAMCONTROLTYPE
_PROGRAMCONTROL_PROGRAMCONTROLTYPE.containing_type = _PROGRAMCONTROL
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Magic'] = _MAGIC
DESCRIPTOR.message_types_by_name['MessageMacAddress'] = _MESSAGEMACADDRESS
DESCRIPTOR.message_types_by_name['MessageResult'] = _MESSAGERESULT
DESCRIPTOR.message_types_by_name['ComputerControl'] = _COMPUTERCONTROL
DESCRIPTOR.message_types_by_name['ProgramControl'] = _PROGRAMCONTROL
DESCRIPTOR.message_types_by_name['HeartBeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['Performance'] = _PERFORMANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.Image)
  })
_sym_db.RegisterMessage(Image)

Magic = _reflection.GeneratedProtocolMessageType('Magic', (_message.Message,), {
  'DESCRIPTOR' : _MAGIC,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.Magic)
  })
_sym_db.RegisterMessage(Magic)

MessageMacAddress = _reflection.GeneratedProtocolMessageType('MessageMacAddress', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEMACADDRESS,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.MessageMacAddress)
  })
_sym_db.RegisterMessage(MessageMacAddress)

MessageResult = _reflection.GeneratedProtocolMessageType('MessageResult', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESULT,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.MessageResult)
  })
_sym_db.RegisterMessage(MessageResult)

ComputerControl = _reflection.GeneratedProtocolMessageType('ComputerControl', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERCONTROL,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.ComputerControl)
  })
_sym_db.RegisterMessage(ComputerControl)

ProgramControl = _reflection.GeneratedProtocolMessageType('ProgramControl', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMCONTROL,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.ProgramControl)
  })
_sym_db.RegisterMessage(ProgramControl)

HeartBeat = _reflection.GeneratedProtocolMessageType('HeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.HeartBeat)
  })
_sym_db.RegisterMessage(HeartBeat)

Performance = _reflection.GeneratedProtocolMessageType('Performance', (_message.Message,), {
  'DESCRIPTOR' : _PERFORMANCE,
  '__module__' : 'wizard_system_pb2'
  # @@protoc_insertion_point(class_scope:WizardSystem.Performance)
  })
_sym_db.RegisterMessage(Performance)


DESCRIPTOR._options = None

_WIZARDSERVICE = _descriptor.ServiceDescriptor(
  name='WizardService',
  full_name='WizardSystem.WizardService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=841,
  serialized_end=982,
  methods=[
  _descriptor.MethodDescriptor(
    name='PostMagicImageRaw',
    full_name='WizardSystem.WizardService.PostMagicImageRaw',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_MAGIC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostMagicImagePng',
    full_name='WizardSystem.WizardService.PostMagicImagePng',
    index=1,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_MAGIC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WIZARDSERVICE)

DESCRIPTOR.services_by_name['WizardService'] = _WIZARDSERVICE

# @@protoc_insertion_point(module_scope)
