# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wizard_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='wizard_api.proto',
  package='WizardApi',
  syntax='proto3',
  serialized_options=b'\252\002\025WizardSystem.Protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10wizard_api.proto\x12\tWizardApi\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\nMagicColor\x12\t\n\x01r\x18\x01 \x01(\x02\x12\t\n\x01g\x18\x02 \x01(\x02\x12\t\n\x01\x62\x18\x03 \x01(\x02\">\n\nMagicImage\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\timageData\x18\x03 \x01(\x0c\"A\n\x05Magic\x12\x0c\n\x04type\x18\x01 \x01(\t\x12*\n\x0bmagicColors\x18\x02 \x03(\x0b\x32\x15.WizardApi.MagicColor2\x8b\x01\n\rWizardService\x12<\n\x11PostMagicImageRaw\x12\x15.WizardApi.MagicImage\x1a\x10.WizardApi.Magic\x12<\n\x11PostMagicImagePng\x12\x15.WizardApi.MagicImage\x1a\x10.WizardApi.MagicB\x18\xaa\x02\x15WizardSystem.Protobufb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MAGICCOLOR = _descriptor.Descriptor(
  name='MagicColor',
  full_name='WizardApi.MagicColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='WizardApi.MagicColor.r', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='g', full_name='WizardApi.MagicColor.g', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='WizardApi.MagicColor.b', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=138,
)


_MAGICIMAGE = _descriptor.Descriptor(
  name='MagicImage',
  full_name='WizardApi.MagicImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='WizardApi.MagicImage.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='WizardApi.MagicImage.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageData', full_name='WizardApi.MagicImage.imageData', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=202,
)


_MAGIC = _descriptor.Descriptor(
  name='Magic',
  full_name='WizardApi.Magic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='WizardApi.Magic.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='magicColors', full_name='WizardApi.Magic.magicColors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=269,
)

_MAGIC.fields_by_name['magicColors'].message_type = _MAGICCOLOR
DESCRIPTOR.message_types_by_name['MagicColor'] = _MAGICCOLOR
DESCRIPTOR.message_types_by_name['MagicImage'] = _MAGICIMAGE
DESCRIPTOR.message_types_by_name['Magic'] = _MAGIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MagicColor = _reflection.GeneratedProtocolMessageType('MagicColor', (_message.Message,), {
  'DESCRIPTOR' : _MAGICCOLOR,
  '__module__' : 'wizard_api_pb2'
  # @@protoc_insertion_point(class_scope:WizardApi.MagicColor)
  })
_sym_db.RegisterMessage(MagicColor)

MagicImage = _reflection.GeneratedProtocolMessageType('MagicImage', (_message.Message,), {
  'DESCRIPTOR' : _MAGICIMAGE,
  '__module__' : 'wizard_api_pb2'
  # @@protoc_insertion_point(class_scope:WizardApi.MagicImage)
  })
_sym_db.RegisterMessage(MagicImage)

Magic = _reflection.GeneratedProtocolMessageType('Magic', (_message.Message,), {
  'DESCRIPTOR' : _MAGIC,
  '__module__' : 'wizard_api_pb2'
  # @@protoc_insertion_point(class_scope:WizardApi.Magic)
  })
_sym_db.RegisterMessage(Magic)


DESCRIPTOR._options = None

_WIZARDSERVICE = _descriptor.ServiceDescriptor(
  name='WizardService',
  full_name='WizardApi.WizardService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=272,
  serialized_end=411,
  methods=[
  _descriptor.MethodDescriptor(
    name='PostMagicImageRaw',
    full_name='WizardApi.WizardService.PostMagicImageRaw',
    index=0,
    containing_service=None,
    input_type=_MAGICIMAGE,
    output_type=_MAGIC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostMagicImagePng',
    full_name='WizardApi.WizardService.PostMagicImagePng',
    index=1,
    containing_service=None,
    input_type=_MAGICIMAGE,
    output_type=_MAGIC,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WIZARDSERVICE)

DESCRIPTOR.services_by_name['WizardService'] = _WIZARDSERVICE

# @@protoc_insertion_point(module_scope)
