# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from .wizard_system_pb2 import *


class WizardServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostMagicImageRaw = channel.unary_unary(
                '/WizardSystem.WizardService/PostMagicImageRaw',
                request_serializer=Image.SerializeToString,
                response_deserializer=Magic.FromString,
                )
        self.PostMagicImagePng = channel.unary_unary(
                '/WizardSystem.WizardService/PostMagicImagePng',
                request_serializer=Image.SerializeToString,
                response_deserializer=Magic.FromString,
                )


class WizardServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostMagicImageRaw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostMagicImagePng(self, request, context):
        """rpc GetMacAddress (google.protobuf.Empty) returns (MessageMacAddress);
        rpc GetHeartBeat (google.protobuf.Empty) returns (HeartBeat);
        rpc GetPerformance (google.protobuf.Empty) returns (Performance);
        rpc PostComputerControlMessage (ComputerControl) returns (google.protobuf.Empty);
        rpc PostProgramControlMessage (ProgramControl) returns (MessageResult);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WizardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostMagicImageRaw': grpc.unary_unary_rpc_method_handler(
                    servicer.PostMagicImageRaw,
                    request_deserializer=Image.FromString,
                    response_serializer=Magic.SerializeToString,
            ),
            'PostMagicImagePng': grpc.unary_unary_rpc_method_handler(
                    servicer.PostMagicImagePng,
                    request_deserializer=Image.FromString,
                    response_serializer=Magic.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WizardSystem.WizardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WizardService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostMagicImageRaw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WizardSystem.WizardService/PostMagicImageRaw',
            Image.SerializeToString,
            Magic.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostMagicImagePng(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WizardSystem.WizardService/PostMagicImagePng',
            Image.SerializeToString,
            Magic.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
