# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x11MessageMacAddress\x12\x12\n\nmacAddress\x18\x01 \x01(\t\"\x85\x01\n\rMessageResult\x12\x30\n\x06result\x18\x01 \x01(\x0e\x32 .MessageResult.MessageResultType\x12\x15\n\rresultMessage\x18\x02 \x01(\t\"+\n\x11MessageResultType\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"\x81\x01\n\x0f\x43omputerControl\x12\x35\n\x07\x63ontrol\x18\x01 \x01(\x0e\x32$.ComputerControl.ComputerControlType\"7\n\x13\x43omputerControlType\x12\t\n\x05START\x10\x00\x12\x0b\n\x07RESTART\x10\x01\x12\x08\n\x04STOP\x10\x02\"\xa5\x01\n\x0eProgramControl\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x13\n\x0bprocessName\x18\x03 \x01(\t\x12\x33\n\x07\x63ontrol\x18\x04 \x01(\x0e\x32\".ProgramControl.ProgramControlType\")\n\x12ProgramControlType\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\"/\n\tHeartBeat\x12\x11\n\tTimestamp\x18\x01 \x01(\t\x12\x0f\n\x07Message\x18\x02 \x01(\t\"\\\n\x0bPerformance\x12\x10\n\x08\x43puUsage\x18\x01 \x01(\x02\x12\x13\n\x0bMemoryUsage\x18\x02 \x01(\x02\x12\x14\n\x0cNetworkUsage\x18\x03 \x01(\x02\x12\x10\n\x08GpuUsage\x18\x04 \x01(\x02\x32\xb7\x02\n\x06Remote\x12;\n\rGetMacAddress\x12\x16.google.protobuf.Empty\x1a\x12.MessageMacAddress\x12\x32\n\x0cGetHeartBeat\x12\x16.google.protobuf.Empty\x1a\n.HeartBeat\x12\x36\n\x0eGetPerformance\x12\x16.google.protobuf.Empty\x1a\x0c.Performance\x12\x46\n\x1aPostComputerControlMessage\x12\x10.ComputerControl\x1a\x16.google.protobuf.Empty\x12<\n\x19PostProgramControlMessage\x12\x0f.ProgramControl\x1a\x0e.MessageResultB\x16\xaa\x02\x13RemoteSystem.Remoteb\x06proto3')



_MESSAGEMACADDRESS = DESCRIPTOR.message_types_by_name['MessageMacAddress']
_MESSAGERESULT = DESCRIPTOR.message_types_by_name['MessageResult']
_COMPUTERCONTROL = DESCRIPTOR.message_types_by_name['ComputerControl']
_PROGRAMCONTROL = DESCRIPTOR.message_types_by_name['ProgramControl']
_HEARTBEAT = DESCRIPTOR.message_types_by_name['HeartBeat']
_PERFORMANCE = DESCRIPTOR.message_types_by_name['Performance']
_MESSAGERESULT_MESSAGERESULTTYPE = _MESSAGERESULT.enum_types_by_name['MessageResultType']
_COMPUTERCONTROL_COMPUTERCONTROLTYPE = _COMPUTERCONTROL.enum_types_by_name['ComputerControlType']
_PROGRAMCONTROL_PROGRAMCONTROLTYPE = _PROGRAMCONTROL.enum_types_by_name['ProgramControlType']
MessageMacAddress = _reflection.GeneratedProtocolMessageType('MessageMacAddress', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEMACADDRESS,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:MessageMacAddress)
  })
_sym_db.RegisterMessage(MessageMacAddress)

MessageResult = _reflection.GeneratedProtocolMessageType('MessageResult', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESULT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:MessageResult)
  })
_sym_db.RegisterMessage(MessageResult)

ComputerControl = _reflection.GeneratedProtocolMessageType('ComputerControl', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERCONTROL,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:ComputerControl)
  })
_sym_db.RegisterMessage(ComputerControl)

ProgramControl = _reflection.GeneratedProtocolMessageType('ProgramControl', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMCONTROL,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:ProgramControl)
  })
_sym_db.RegisterMessage(ProgramControl)

HeartBeat = _reflection.GeneratedProtocolMessageType('HeartBeat', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEAT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeat)
  })
_sym_db.RegisterMessage(HeartBeat)

Performance = _reflection.GeneratedProtocolMessageType('Performance', (_message.Message,), {
  'DESCRIPTOR' : _PERFORMANCE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:Performance)
  })
_sym_db.RegisterMessage(Performance)

_REMOTE = DESCRIPTOR.services_by_name['Remote']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023RemoteSystem.Remote'
  _MESSAGEMACADDRESS._serialized_start=76
  _MESSAGEMACADDRESS._serialized_end=115
  _MESSAGERESULT._serialized_start=118
  _MESSAGERESULT._serialized_end=251
  _MESSAGERESULT_MESSAGERESULTTYPE._serialized_start=208
  _MESSAGERESULT_MESSAGERESULTTYPE._serialized_end=251
  _COMPUTERCONTROL._serialized_start=254
  _COMPUTERCONTROL._serialized_end=383
  _COMPUTERCONTROL_COMPUTERCONTROLTYPE._serialized_start=328
  _COMPUTERCONTROL_COMPUTERCONTROLTYPE._serialized_end=383
  _PROGRAMCONTROL._serialized_start=386
  _PROGRAMCONTROL._serialized_end=551
  _PROGRAMCONTROL_PROGRAMCONTROLTYPE._serialized_start=510
  _PROGRAMCONTROL_PROGRAMCONTROLTYPE._serialized_end=551
  _HEARTBEAT._serialized_start=553
  _HEARTBEAT._serialized_end=600
  _PERFORMANCE._serialized_start=602
  _PERFORMANCE._serialized_end=694
  _REMOTE._serialized_start=697
  _REMOTE._serialized_end=1008
# @@protoc_insertion_point(module_scope)
